### PR TITLE
Bunch of SEO fixes

### PR DESCRIPTION
**Pull request by peterj**
- move the meta tags to a separate file
- add Twitter card image URL
- add GA to config (and move it out of head.html)
- add extra tags for the blog pages

### CODE REVIEW

**Comment by lunchboxav** [comment]
Thank you very much for working on this @peterj, really appreciate it. The changes looks great. 

However, regarding the GA code, previously, I put that code in config.toml, however it gave me no data in Google Analytics. That's why I put the script in head. Do you have any suggestions on this?

**Review by lunchboxav — APPROVED** [review]
I think we can merge it, but let's just monitor the Google Analytics. If no new data are coming in, then we can revert the change back.

**Comment by peterj** [comment]
I checked the generated page (view source), and it does create the GA script and all that.
Screen Shot 2021-02-10 at 2 52 11 PM

**Comment by lunchboxav** [comment]
Yes it does, that's why I was confused why I didn't get any data. Regardless, let's merge it. Thank you very much for this Peter 🙏

**Pull request merged**
