### PR TITLE
Removing partnership items for now

### PR DESCRIPTION
**Pull request by pmerrison**
The partnership items are currently not fit for purpose.  Until we have integration guides for these partners we're going to hide the content by moving it somewhere that Hugo won't render.

### CODE REVIEW

**Comment by rootsongjc** [comment]
Although you move the position of each subpage, the tab partner still exists and you need to modify the configuration of the home page from `config.toml`.

**Comment by incfly** [comment]
https://deploy-preview-252--getistio-demo.netlify.app/partners/

I guess Jimmy means this page. Rendered as 404 right now.

**Comment by rootsongjc** [comment]
@incfly Yes, it is, remove the `[[Languages.en.menu.main]]` and `[[Languages.zh.menu.main]]` sections from `config.toml` will solve this problem.

**Review by rootsongjc — APPROVED** [review]
Merge this, then I will update the config.yaml

**Pull request merged**
