### PR TITLE
Make sure in-eks is nested under install-istio

### PR DESCRIPTION
**Pull request by dio**
This makes sure we have a "root" "Istio install" menu, and no more rendering duplication.

Preview:

image

Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

### CODE REVIEW

**Comment by PetrMc** [comment]
Hi @dio thanks for it, but need a bit more of your help.

(1) I'm attaching video here - submenus are not accessible for any topics - unless user is directed to a subtopic and then menu is extended in navigation bar.


(2) need a bit more understanding what was happening and why cleaning up markdown removed the `Install Istio` from the root menu. We're doing bunch of changes to the website and without understanding will step in the problem again.

🙇

**Comment by dio** [comment]
Yo @PetrMc, I coordinated offline with @nascode. He will provide support for this repo. 

@nascode since this is actually "docs", I believe this is under your jurisdiction :).

**Comment by dio** [comment]
BTW, @PetrMc are you accessing: https://deploy-preview-271--getistio-demo.netlify.app/getmesh-cli/? Or locally?

If locally you need to follow the merged changes to README.md https://github.com/tetratelabs/istio-distro.io/commit/c03fe59ae6a3de2db654536dfc8640db2b338ac4.

Basically, for now, you need to use hugo v0.8.5 extended and node12 (to match the current Netlify env).

**Comment by nascode** [comment]
Hi @PetrMc 

For (1) if you want to test locally, make sure you are using Hugo binary v0.8.5 extended to have same behavior with production build. As for Node, I am using Node v16 successfully. You can get the binary here https://github.com/gohugoio/hugo/releases/tag/v0.85.0 (choose the extended version)

For (2) can you elaborate more?

**Comment by PetrMc** [comment]
Thanks @nascode and @dio - i tried 0.8.0 earlier woth no luck and will test with 0.8.5 (node 12) tonite and report back.

@nascode For (2) need to understand what caused the install page to be duplicated in two places including root of navbar. So we can avoid making the same mistake again when adding the content.

Btw is there a lint / editor you use as manually updating markdown is lengthy and fields like "date" in header often get ignored?

**Comment by PetrMc** [comment]
@dio / @nascode - first of all - thank you without your help I would be still scratching my had.
- 0.85.0 / Node 12 works as expected
- Looking at this PR and experementing in a fork - it seems that the rules are:
    - `type: docs` only acceptable for the top level menus - all subdirectories need to be removed
    - the directory names should be shorter 
    - if there is no subdirectories - one with _index.md and `hidden: true` header is required
   there are maybe one or two more that I can't recall

my proposition is to not apply this PR but instead I'll be submitting a new one shortly - that implements the changes here. 

hopefully we can apply that one instead as there a lot of context that @ogarrett and myself have reworked for Monday 4PM AWS announcement. (it's when this stuff will go live)

**Comment by dio** [comment]
AH, OK. very cool. To be honest that was my first time reading this repo. :). Will close the issue.

**Comment by PetrMc** [comment]
> AH, OK. very cool. To be honest that was my first time reading this repo. :). Will close the repo.

Hope you mean - close PR, not Repo :-) Thanks for helping! 🙇

**Pull request closed without merging**
