### PR TITLE
allow WF restart to rebuild site

### PR DESCRIPTION
**Pull request by psbrar99**

### CODE REVIEW

**Review by sbko — APPROVED** [review]

**Comment by dio** [comment]
I don't think we use gh-pages. Not sure why we have this workflow.

**Comment by psbrar99** [comment]
@dio : https://istio.tetratelabs.io (getistio-demo.netlify.app) is using this no ?
we want to update this [page]( https://istio.tetratelabs.io/download) whenever we have new releases. atm rebuilding the site does the trick?

**Comment by dio** [comment]
@psbrar99 No. I think you can trigger rebuilding the site using build hooks (https://docs.netlify.com/configure-builds/build-hooks). 

Now we have a workflow for it: https://github.com/tetratelabs/istio-distro.io/actions/workflows/update-manifest.yaml

You can manually trigger it (it is also scheduled) via page or CLI:

```console
gh workflow run update-manifest.yaml -R tetratelabs/istio-distro.io
```

**Comment by dio** [comment]
Or, I have a PR on https://github.com/tetratelabs/helm-charts/pull/44 so when you update (read: merge changes on) that manifest.json, it will trigger a build.

**Comment by psbrar99** [comment]
super helpful!
thank you @dio. This is interesting, not sure how the existing workflow was able to refresh the website?
i  saw the changes happening in gh-pages [branch](https://github.com/tetratelabs/istio-distro.io/commits/gh-pages)  and corresponding effects on the website. Thank you for clarification.

**Comment by dio** [comment]
AFAIK, looking at the config https://app.netlify.com/sites/getistio-demo/configuration/deploys we only care when something is happening on `main` branch.

image

The build deploy logs inspector also shows the same thing:

image

**Pull request merged**
