### PR TITLE
empty commit to restart webserver

### PR DESCRIPTION
**Pull request by psbrar99**
The [content](https://istio.tetratelabs.io/download/)  here is cached, need to restart the server to reflect new getmesh builds.

### CODE REVIEW

**Comment by arkodg** [comment]
not sure I understand this @psbrar99, shouldnt the script fetch the release from https://github.com/tetratelabs/getmesh/releases/tag/latest

**Comment by psbrar99** [comment]
@arkodg: i think it scraps the manifest.json to get the builds.
https://github.com/tetratelabs/istio-distro.io/blob/main/layouts/shortcodes/downloads.html#L34
There was some issue with nodejs that requires the server restart.
@PetrMc  has better understanding and can confirm?

**Comment by arkodg** [comment]
> @arkodg: i think it scraps the manifest.json to get the builds.
> https://github.com/tetratelabs/istio-distro.io/blob/main/layouts/shortcodes/downloads.html#L34
> There was some issue with nodejs that requires the server restart.
> @PetrMc has better understanding and can confirm?

@psbrar99 can this be solved using a GHA in this repo, that tracks releases in getmesh ?

**Comment by psbrar99** [comment]
@arkodg : i am not sure, lets wait for @PetrMc comment.
getmesh [release](https://github.com/tetratelabs/getmesh/releases) just reads manifest.json to reflect the builds, i am not sure how caching work or its just completely static.
We should be able to trigger the CI by tracking any changes in getmesh repo but it involves 2 repos and sharing PAT.

**Review by arkodg — APPROVED** [review]
approving for now, can you please raise a GH issue to automate this in the future

**Review by arkodg — APPROVED** [review]

**Pull request merged**
