### PR TITLE
istio 1.9 update for external ca

### PR DESCRIPTION
**Pull request by smarunich**
Istio 1.9 Operator won't permit the config map definition with secret reference and in fact the volume mount is configmap, not secret.

```
            value:
              name: ca-root-cert
              configMap:
                -secretName: istiod-tls
                defaultMode: 420
                name: istio-ca-root-cert
```

### CODE REVIEW

**Review by yskopets — APPROVED** [review]
Notice that there is an overlap with another PR in progress - https://github.com/tetratelabs/istio-distro.io/pull/244

**Comment by peterj** [comment]
@smarunich is this PR still relevant?

**Comment by PetrMc** [comment]
@smarunich - what is the current status here?

**Comment by dio** [comment]
@smarunich should we close this?

**Pull request closed without merging**
