### PR TITLE
Context update

### PR DESCRIPTION
**Pull request by PetrMc**
The context is getting updated in preparation for AWS launch of Add-on on Monday November 28 4 PM PST.

*the PR should not be merged before annoncment that will be confirmed by @saptak*

this PR is not the complete new state of the docs but the first step of bringing the docs up to date. Thanks to @ogarrett for the majority of work (that has been done at lightning pace)

also PR replaces the @dio / @nascode https://github.com/tetratelabs/istio-distro.io/pull/271 that to address side navigation issue that we faced.

### CODE REVIEW

**Comment by PetrMc** [comment]
@dio @nascode and @ogarrett - would appreciate you noticing / correcting anything before the website update.

Thanks!

**Comment by dio** [comment]
Note that everything under reference will be replaced by: https://github.com/tetratelabs/getmesh/blob/75da87b0ed2c453a8579795f1f1fa327c6a98e98/.github/workflows/release.yaml#L51-L69 (the workflow will push directly to `main` branch ⚡️).

For more auto generated pages: https://github.com/tetratelabs/istio-distro.io#auto-generated-pages.

**Comment by dio** [comment]
FTR the preview is on https://deploy-preview-273--getistio-demo.netlify.app/.

**Comment by nascode** [comment]
@PetrMc From the url preview, I think the docs site works fine. As for the content per page, there might be better person to check.

**Comment by PetrMc** [comment]
Thanks all! reviewed by @ogarrett offline and via https://github.com/tetratelabs/istio-distro.io/pull/274

**Pull request merged**
