### PR TITLE
Change download URLs from bintray to cloudsmith

### PR DESCRIPTION
**Pull request by arkodg**
Relates to : https://github.com/tetratelabs/getistio/pull/36

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

### CODE REVIEW

**Review by oktocat — APPROVED** [review]
let's not forget to put CS logo somewhere as well : )

**Comment by arkodg** [comment]
good call @oktocat, raised an issue

**Review by oktocat — CHANGES_REQUESTED** [review]
~look, I'll block this one until Zack and I do the CNAME setup, just so we don't do the same work twice.~
:man_facepalming: wrong PR lol

**Review by oktocat — APPROVED** [review]

**Comment by lunchboxav** [comment]
As I need to update the content to the website, I'll merge this @arkodg

**Pull request merged**
